spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/dissertation
    username: postgres
    password: root123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    #show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL81Dialect
login.cred: abc
#Metrics related configurations
management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
server:
  port: 8081
grpc.server.port: 8083